name: iOS starter workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [14.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Build and test
        run: |
          xcodebuild -workspace AutoShow.xcworkspace -scheme AutoShow -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build test
