name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: List runner info
      run: sw_vers && arch
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version

  build-release:
    name: Build release
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
    - name: Build
      run: set -o pipefail && xcodebuild -configuration Release -scheme AutoShow -sdk iphonesimulator -destination 'platform=iOS Simulator,id=02A210DA-73F3-45AB-975A-9003C1E9B9D4' CODE_SIGNING_ALLOWED='NO'
